### ISSUE TITLE
CMAKE_HAVE_LIBC_PTHREAD -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed

### ISSUE THREAD

**Issue by ShilpiPhadnis** [riebl/artery#103] opened 2019-12-12 04:38 UTC
Dear Riebl,
We are trying to implement raw socket in artery application. We copied necessary files of vanetza-tools-socktapcam in vanetza geonet and implement raw socket in AccessInterface file.
We are able to build all libraries INET, Vanetza and Veins properly but we are facing issue during cmake.
Kindly confirm why we are facing this issue?

**Comment by kenog** [comment] 2019-12-12 06:04
Please provide the content of `build/CMakeFiles/CMakeError.log`. Which compiler do you use?

**Comment by ShilpiPhadnis** [comment] 2019-12-12 11:10
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp
Run Build Command(s):/usr/bin/make cmTC_9d353/fast && /usr/bin/make -f CMakeFiles/cmTC_9d353.dir/build.make CMakeFiles/cmTC_9d353.dir/build
make[1]: Entering directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9d353.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD -o CMakeFiles/cmTC_9d353.dir/src.c.o -c /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_9d353
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9d353.dir/link.txt --verbose=1
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD -rdynamic CMakeFiles/cmTC_9d353.dir/src.c.o -o cmTC_9d353
CMakeFiles/cmTC_9d353.dir/src.c.o: In function main':
src.c:(.text+0x3c): undefined reference topthread_create'
src.c:(.text+0x48): undefined reference to pthread_detach'
src.c:(.text+0x59): undefined reference topthread_join'
src.c:(.text+0x6d): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_9d353.dir/build.make:86: recipe for target 'cmTC_9d353' failed
make[1]: *** [cmTC_9d353] Error 1
make[1]: Leaving directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_9d353/fast' failed
make: *** [cmTC_9d353/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
return data;
}

int main(void)
{
pthread_t thread;
pthread_create(&thread, NULL, test_func, NULL);
pthread_detach(thread);
pthread_join(thread, NULL);
pthread_atfork(NULL, NULL, NULL);
pthread_exit(NULL);

return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_cdaa2/fast && /usr/bin/make -f CMakeFiles/cmTC_cdaa2.dir/build.make CMakeFiles/cmTC_cdaa2.dir/build
make[1]: Entering directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_cdaa2.dir/CheckFunctionExists.c.o
/usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_cdaa2.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.15/Modules/CheckFunctionExists.c
Linking C executable cmTC_cdaa2
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cdaa2.dir/link.txt --verbose=1
/usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create -rdynamic CMakeFiles/cmTC_cdaa2.dir/CheckFunctionExists.c.o -o cmTC_cdaa2 -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 ffexit status
CMakeFiles/cmTC_cdaa2.dir/build.make:86: recipe for target 'cmTC_cdaa2' failed
make[1]: *** [cmTC_cdaa2] Error 1
make[1]: Leaving directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_cdaa2/fast' failed
make: *** [cmTC_cdaa2/fast] Error 2

**Comment by ShilpiPhadnis** [comment] 2019-12-13 07:02
Any idea how to solve this issue ?

**Comment by riebl** [comment] 2019-12-13 11:52
You may add `-pthread` to `CMAKE_EXE_LINKER_FLAGS` and check if this solves your issue. However, I cannot see where pthread should have been added as dependency in the first place.

**Comment by ShilpiPhadnis** [comment] 2019-12-17 09:04
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_41f9f/fast && /usr/bin/make -f CMakeFiles/cmTC_41f9f.dir/build.make CMakeFiles/cmTC_41f9f.dir/build
make[1]: Entering directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_41f9f.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_41f9f.dir/src.c.o   -c /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_41f9f
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_41f9f.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_41f9f.dir/src.c.o  -o cmTC_41f9f 
CMakeFiles/cmTC_41f9f.dir/src.c.o: In function `main':
src.c:(.text+0x3c): undefined reference to `pthread_create'
src.c:(.text+0x48): undefined reference to `pthread_detach'
src.c:(.text+0x59): undefined reference to `pthread_join'
src.c:(.text+0x6d): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_41f9f.dir/build.make:86: recipe for target 'cmTC_41f9f' failed
make[1]: *** [cmTC_41f9f] Error 1
make[1]: Leaving directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_41f9f/fast' failed
make: *** [cmTC_41f9f/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_f0b19/fast && /usr/bin/make -f CMakeFiles/cmTC_f0b19.dir/build.make CMakeFiles/cmTC_f0b19.dir/build
make[1]: Entering directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f0b19.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_f0b19.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.15/Modules/CheckFunctionExists.c
Linking C executable cmTC_f0b19
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f0b19.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_f0b19.dir/CheckFunctionExists.c.o  -o cmTC_f0b19 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_f0b19.dir/build.make:86: recipe for target 'cmTC_f0b19' failed
make[1]: *** [cmTC_f0b19] Error 1
make[1]: Leaving directory '/home/shilpip/Desktop/ShilpiPhadnis/Artery/arter_inet4_raw/artery-inet4/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_f0b19/fast' failed
make: *** [cmTC_f0b19/fast] Error 2

Still the same error. after adding above line. Even I am not sure why it is takind pthread.

**Comment by riebl** [comment] 2019-12-17 09:36
The output you have posted includes ` /usr/bin/ld: cannot find -lpthreads` but the library is actually called `pthread`. I guess you have made a typo.

**Comment by riebl** [comment] 2020-04-17 14:51
No reply, closing.

**Closed by riebl** 2020-04-17 14:51 UTC

**Comment by Liveshkumar** [comment] 2021-09-13 17:17
this is too late. but it will help other. use  this link https://stackoverflow.com/questions/31948521/building-error-using-cmake-cannot-find-lpthreads . The issue is not with the lpthreads. If we have lpthreads issue it won't affect the running. So try to debug other errors. If we do so means it working well
